# default profile settings
spring:
  profiles:
    active: local
springdoc:
  swagger-ui:
    path: /swagger
  cache:
    disabled: true
  use-fqn: true

---

# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create #auto
        default_batch_fetch_size: 1000

---

# develop profile
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: ${aws.db.url}
    username: ${aws.db.username}
    password: ${aws.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        format_sql: true
        #        show_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create #auto
        default_batch_fetch_size: 1000